using UnityEngine;

public class Achievements : MonoBehaviour {
	public static int IS_ACHIEVEMENT_FIRST_WIN;
	public static int IS_ACHIEVEMENT_NEW_SKIN;
	public static int IS_ACHIEVEMENT_MULTI_PULTI;
	public static int IS_ACHIEVEMENT_MISS_CLICK;
	public static int IS_ACHIEVEMENT_GET_MAX;
	public static int IS_ACHIEVEMENT_THREE_JUMPS;

	public static int IS_ACHIEVEMENT_MASTER;
	public static int IS_ACHIEVEMENT_FiFIELD_OF_CANDIES;
	public static int IS_ACHIEVEMENT_EXPLOSIVE;
	public static int IS_ACHIEVEMENT_COLLECTION;
	
	void Awake () {
		IS_ACHIEVEMENT_FIRST_WIN = PlayerPrefs.GetInt("IS_ACHIEVEMENT_FIRST_WIN", 0);
		IS_ACHIEVEMENT_NEW_SKIN = PlayerPrefs.GetInt("IS_ACHIEVEMENT_NEW_SKIN", 0);
		IS_ACHIEVEMENT_MULTI_PULTI = PlayerPrefs.GetInt("IS_ACHIEVEMENT_MULTI_PULTI", 0);
		IS_ACHIEVEMENT_MISS_CLICK = PlayerPrefs.GetInt("IS_ACHIEVEMENT_MISS_CLICK", 0);
		IS_ACHIEVEMENT_GET_MAX = PlayerPrefs.GetInt("IS_ACHIEVEMENT_GET_MAX", 0);
		IS_ACHIEVEMENT_THREE_JUMPS = PlayerPrefs.GetInt("IS_ACHIEVEMENT_THREE_JUMPS", 0);
		IS_ACHIEVEMENT_MASTER = PlayerPrefs.GetInt("IS_ACHIEVEMENT_MASTER", 0);
		IS_ACHIEVEMENT_FiFIELD_OF_CANDIES = PlayerPrefs.GetInt("IS_ACHIEVEMENT_FiFIELD_OF_CANDIES", 0);
		IS_ACHIEVEMENT_EXPLOSIVE = PlayerPrefs.GetInt("IS_ACHIEVEMENT_EXPLOSIVE", 0);
		IS_ACHIEVEMENT_COLLECTION = PlayerPrefs.GetInt("IS_ACHIEVEMENT_COLLECTION", 0);
	}
	

}
